name: Issue management
on:
    issues:
        types: [ closed ]

jobs:
    not_planned_issue:
        name: Message about not planned issue
        runs-on: ubuntu-latest
        if: ${{ github.event.issue && github.event.action == 'closed' && github.event.issue.state_reason == 'not_planned' }}
        steps:
            - name: Print message
              env:
                ISSUE_NUMBER: ${{ github.event.issue.number }}
              run: |
                echo "not planned issue: $ISSUE_NUMBER"

    completed_issue:
        name: Message about completed issue
        runs-on: ubuntu-latest
        if: ${{ github.event.issue && github.event.action == 'closed' && github.event.issue.state_reason == 'completed' }}
        steps:
            - name: Print message
              env:
                ISSUE_NUMBER: ${{ github.event.issue.number }}
              run: |
                echo "completed issue: $ISSUE_NUMBER"
