name: Pre-release
on:
    release:
        types: [ published, edited ]

jobs:
    hello:
        name: Hello World
        runs-on: ubuntu-latest
        if: ${{ github.event.release.prerelease }}
        steps:
            - name: Print message
              run: echo "Hello World"
