name: Pre-release

on:
    workflow_dispatch:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+-[a-z]+'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

# condition for running jobs
# github.event_name == workflow_dispatch || github.event_name == push || github.event.release.prerelease

jobs:
    hello:
        name: Hello World
        runs-on: ubuntu-latest
        env:
            REF: ${{ github.ref }}
            SHA: ${{ github.sha }}
            REF_NAME: ${{ github.ref_name }}
            ACTION: ${{ github.event.action }}
            PRERELEASE: ${{ github.event.release.prerelease }}
            EVENT_NAME: ${{ github.event_name }}
        steps:
            - name: Print message
              run: |
                echo "ref: $REF"
                echo "ref_name: $REF_NAME"
                echo "sha: $SHA"
                echo "action: $ACTION"
                echo "pre-release: $PRERELEASE"
                echo "event_name: $EVENT_NAME"
