name: Pre-release

on:
    workflow_dispatch:
    release:
        types: [ prereleased ]

jobs:
    hello:
        name: Hello World
        runs-on: ubuntu-latest
        if: ${{ github.event.release.prerelease }}
        steps:
            - name: Print message
              run: echo "Hello World"
