name: Checks
on:
    workflow_dispatch:
    pull_request:
        types: [ opened, synchronize, unlabeled ]
        paths-ignore:
            - 'docs/**'
    push:
        branches:
            - main
        paths-ignore:
            - 'docs/**'

jobs:
    hello:
        name: Hello World
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'WIP') && !(github.event.action == 'unlabeled' && github.event.label.name != 'WIP') }}
        # if: "!contains(github.event.pull_request.labels.*.name, 'WIP')"
        steps:
            - name: Print message
              run: echo "Hello World"
